name: Feature Request
description: Suggest an idea for this library
title: "[FR] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature request.
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Why do you need this feature?
